image: python:3.13

stages:
  - build
  - test
  - docker-build

variables:
  ACR_LOGIN_SERVER: sliceacr.azurecr.io
  ACR_NAME: sliceacr
  WEBAPP_NAME: slice-haven
  DOCKER_IMAGE_TAG: latest

cache:
  paths:
    - ~/.cache/pip

build:
  stage: build
  script:
    - echo "building ..."
    - pip install -r requirements.txt


test:
  stage: test
  script:
    - echo "testing ..."
    - pip install -r requirements.txt
    - pytest -v

docker_build:
  image: mcr.microsoft.com/azure-cli:2.69.0
  stage: docker-build
  services:
    - docker:24-dind
  script:
    - echo "Logging in to Azure..."
    - az login --service-principal -u $appId -p $password --tenant $tenant
    - az acr login --name $ACR_NAME
    - echo "Building Docker image..."
    - docker build -t $ACR_LOGIN_SERVER/$WEBAPP_NAME:$DOCKER_IMAGE_TAG .
    - echo "Pushing Docker image to ACR..."
    - docker push $ACR_LOGIN_SERVER/$WEBAPP_NAME:$DOCKER_IMAGE_TAG
