"""initila migration

Revision ID: 0ae61ac4e402
Revises: 
Create Date: 2025-12-27 14:49:59.500172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae61ac4e402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('client', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drink_data')
    op.drop_table('order_data')
    op.drop_table('pizza_data')
    op.drop_table('salad_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salad_data',
    sa.Column('salad_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('salad_id')
    )
    op.create_table('pizza_data',
    sa.Column('pizza_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('pizza_id')
    )
    op.create_table('order_data',
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('client', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('drink_data',
    sa.Column('drink_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('image_path', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('drink_id')
    )
    op.drop_table('salad')
    op.drop_table('pizza')
    op.drop_table('order')
    op.drop_table('drink')
    # ### end Alembic commands ###
